inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - test/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/EndAlignment:
  AlignWith: variable

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/PerlBackrefs:
  Enabled: false