AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - test/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/EndAlignment:
  AlignWith: variable

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/PerlBackrefs:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Exclude:
    - 'db/models.rb'
    - 'lib/string_infinity.rb'
    - 'lib/yap/active_record/relation.rb'
    - 'lib/yap/column_mapper.rb'
    - 'lib/yap/filter.rb'
    - 'lib/yap/filterable.rb'
