AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - test/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/CaseIndentation:
  EnforcedStyle: end

Style/PerlBackrefs:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/string_infinity.rb'
    - 'lib/yap/active_record/relation.rb'
    - 'lib/yap/column_mapper.rb'
    - 'lib/yap/filter.rb'
    - 'lib/yap/filterable.rb'
